import { ShoppingBagIcon, StarIcon, CubeIcon, PencilIcon, CheckCircleIcon, PackageIcon, PlusIcon } from "~/components/icons";

export const MOCK_PLANT = {
  id: "plant-001",
  slug: "monstera-deliciosa-albo",
  status: "ACTIVE" as string,
  thumbnail: {
    id: "media-001",
    url: null as string | null,
  },
  name: "Monstera Deliciosa Albo",
  shortDescription: "Stunning variegated Monstera with white-marbled leaves. A true collector's piece.",
  description: "The Monstera Deliciosa Albo Variegata is one of the most sought-after houseplants in the world. Each leaf features unique white variegation patterns that make every plant truly one-of-a-kind. This tropical beauty is native to Central American rainforests and can grow up to 30 feet in the wild, though typically stays much smaller as a houseplant.",
  scientificName: "Monstera deliciosa 'Albo Variegata'",
  category: {
    id: "cat-001",
    slug: "indoor-plants",
    name: "Indoor Plants",
  },
  tags: [
    { id: "tag-001", slug: "variegated", name: "Variegated" },
    { id: "tag-002", slug: "rare", name: "Rare" },
    { id: "tag-003", slug: "collector-item", name: "Collector's Item" },
    { id: "tag-004", slug: "indoor", name: "Indoor" },
  ],
  price: "4500.00",
  inventoryCount: 12,
  createdAt: "2025-12-15T10:30:00Z",
  updatedAt: "2026-05-01T14:22:00Z",

  plantDetails: {
    lightRequirement: "BRIGHT_INDIRECT",
    wateringFrequency: "WEEKLY",
    humidityLevel: "HIGH",
    careDifficulty: "INTERMEDIATE",
    growthRate: "MODERATE",
    temperatureRange: "18-27°C",
    matureHeight: "1.5-3m",
    matureSpread: "0.6-1.2m",
    translations: {
      en: {
        commonNames: "Albo Monstera, White Variegated Monstera, Ceriman",
        origin: "Central America (Panama, southern Mexico)",
        soilType: "Well-draining aroid mix (orchid bark, perlite, peat)",
        toxicityInfo: "Toxic to cats and dogs if ingested. Contains calcium oxalate crystals.",
      },
      bn: {
        commonNames: "অ্যালবো মনস্টেরা, সাদা দাগওয়ালা মনস্টেরা",
        origin: "মধ্য আমেরিকা (পানামা, দক্ষিণ মেক্সিকো)",
        soilType: "সু-nিষ্কাশনকারী অরয়েড মিক্স",
        toxicityInfo: "বিড়াল ও কুকুরের জন্য বিষাক্ত।",
      },
    },
  },

  variants: [
    {
      id: "var-001",
      sku: "ALBO-MED-001",
      price: 4500,
      inventoryCount: 8,
      trackInventory: true,
      lowStockThreshold: 3,
      isBase: true,
      isActive: true,
      attributes: {
        growthStage: "MATURE",
        plantForm: "UPRIGHT",
        variegation: "ALBO",
        leafDensity: "DENSE",
        stemCount: 3,
        currentHeight: "45cm",
        currentSpread: "35cm",
        propagationType: "CUTTING",
        containerType: "NURSERY_POT",
        containerSize: "15cm",
      },
      images: [
        { id: "img-001", url: null, alt: "Front view" },
        { id: "img-002", url: null, alt: "Side view" },
        { id: "img-003", url: null, alt: "Leaf detail" },
      ],
    },
    {
      id: "var-002",
      sku: "ALBO-SML-002",
      price: 2800,
      inventoryCount: 4,
      trackInventory: true,
      lowStockThreshold: 2,
      isBase: false,
      isActive: true,
      attributes: {
        growthStage: "JUVENILE",
        plantForm: "UPRIGHT",
        variegation: "ALBO",
        leafDensity: "MODERATE",
        stemCount: 1,
        currentHeight: "25cm",
        currentSpread: "20cm",
        propagationType: "CUTTING",
        containerType: "NURSERY_POT",
        containerSize: "10cm",
      },
      images: [] as { id: string; url: null; alt: string }[],
    },
  ],

  careGuide: {
    en: {
      lightInstructions: "Provide bright indirect light. Avoid direct sunlight which can scorch the white variegated portions. An east-facing window is ideal.",
      wateringInstructions: "Water when the top 2-3 inches of soil are dry. Typically every 7-10 days. Ensure proper drainage to prevent root rot.",
      humidityInstructions: "Maintain humidity above 60%. Use a humidifier or pebble tray. Mist leaves regularly in dry conditions.",
      fertilizerSchedule: "Feed with balanced liquid fertilizer (20-20-20) diluted to half strength every 2-4 weeks during growing season (spring-summer).",
      repottingFrequency: "Repot every 12-18 months or when roots emerge from drainage holes. Use fresh aroid mix.",
      pruningNotes: "Remove yellow or damaged leaves at the stem base. Prune to control size and encourage bushier growth.",
      commonProblems: "Brown leaf edges (low humidity), yellowing leaves (overwatering), loss of variegation (insufficient light), root rot (poor drainage).",
      seasonalCare: "Reduce watering in winter. Maintain consistent temperature. Avoid cold drafts and heating vents.",
    },
    bn: {
      lightInstructions: "উজ্জ্বল পরোক্ষ আলো দিন। সরাসরি সূর্যের আলো এড়িয়ে চলুন।",
      wateringInstructions: "মাটির উপরের ২-৩ ইঞ্চি শুকিয়ে গেলে পানি দিন। সাধারণত প্রতি ৭-১০ দিনে।",
      humidityInstructions: "আর্দ্রতা ৬০% এর উপরে রাখুন। হিউমিডিফায়ার ব্যবহার করুন।",
      fertilizerSchedule: "বৃদ্ধির মৌসুমে প্রতি ২-৪ সপ্তাহে ভারসাম্যপূর্ণ সার দিন।",
      repottingFrequency: "প্রতি ১২-১৮ মাসে পুনরায় পোট করুন।",
      pruningNotes: "হলুদ বা ক্ষতিগ্রস্ত পাতা কাটুন।",
      commonProblems: "বাদামী পাতার প্রান্ত (কম আর্দ্রতা), হলুদ পাতা (অতিরিক্ত পানি)।",
      seasonalCare: "শীতকালে পানির পরিমাণ কমান।",
    },
  },
};

export const MOCK_STATS = {
  totalViews: 2847,
  viewsThisMonth: 423,
  totalOrders: 156,
  ordersThisMonth: 23,
  totalRevenue: "702000.00",
  revenueThisMonth: "103500.00",
  avgRating: 4.6,
  totalReviews: 89,
  conversionRate: 5.5,
  stockTurnover: 3.2,
  viewsByPeriod: [
    { period: "7 days", value: 98, change: "+12%" },
    { period: "30 days", value: 423, change: "+8%" },
    { period: "90 days", value: 1247, change: "+23%" },
  ],
  ordersByPeriod: [
    { period: "7 days", value: 5, change: "-2%" },
    { period: "30 days", value: 23, change: "+15%" },
    { period: "90 days", value: 67, change: "+31%" },
  ],
  revenueByPeriod: [
    { period: "7 days", value: "22,500", change: "-2%" },
    { period: "30 days", value: "1,03,500", change: "+15%" },
    { period: "90 days", value: "3,01,500", change: "+31%" },
  ],
};

export const MOCK_REVIEWS = [
  {
    id: "rev-001",
    customerName: "Rahima Begum",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Absolutely stunning plant!",
    comment: "The variegation on this Monstera is incredible. Each leaf has unique white patterns. It arrived well-packaged and healthy. Already producing new leaves!",
    date: "2026-04-28T10:00:00Z",
    timeAgo: "10 days ago",
    verifiedPurchase: true,
    images: ["img-review-001", "img-review-002"],
    helpful: 12,
  },
  {
    id: "rev-002",
    customerName: "Karim Ahmed",
    customerAvatar: null as string | null,
    rating: 4,
    title: "Beautiful but needs care",
    comment: "Great plant overall. The variegation is good though not as white as the photos. It's adapting well to my home. Would recommend for experienced plant parents.",
    date: "2026-04-25T14:30:00Z",
    timeAgo: "13 days ago",
    verifiedPurchase: true,
    images: ["img-review-003"],
    helpful: 8,
  },
  {
    id: "rev-003",
    customerName: "Fatima Khan",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Perfect condition, fast delivery",
    comment: "Packaging was excellent. Plant arrived vibrant and healthy. Already has a new leaf unfurling. Very happy with this purchase!",
    date: "2026-04-20T09:15:00Z",
    timeAgo: "18 days ago",
    verifiedPurchase: true,
    images: [] as string[],
    helpful: 15,
  },
  {
    id: "rev-004",
    customerName: "Sunny Das",
    customerAvatar: null as string | null,
    rating: 3,
    title: "Decent plant, some issues",
    comment: "Plant is okay but had some brown edges on arrival. New growth looks healthy though. Variegation is more cream than pure white.",
    date: "2026-04-15T16:45:00Z",
    timeAgo: "23 days ago",
    verifiedPurchase: true,
    images: ["img-review-004"],
    helpful: 5,
  },
  {
    id: "rev-005",
    customerName: "Nusrat Jahan",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Best Albo I've seen locally",
    comment: "I've ordered from multiple sellers and this is by far the best quality Albo Monstera available locally. The variegation is stunning and the plant is very healthy.",
    date: "2026-04-10T11:20:00Z",
    timeAgo: "28 days ago",
    verifiedPurchase: true,
    images: ["img-review-005", "img-review-006", "img-review-007"],
    helpful: 22,
  },
];

export const MOCK_REVIEWS_SUMMARY = {
  average: 4.6,
  total: 89,
  distribution: [
    { stars: 5, count: 62, percentage: 69.7 },
    { stars: 4, count: 18, percentage: 20.2 },
    { stars: 3, count: 6, percentage: 6.7 },
    { stars: 2, count: 2, percentage: 2.2 },
    { stars: 1, count: 1, percentage: 1.1 },
  ],
  highlights: [
    { label: "Healthy arrival", count: 45 },
    { label: "Good variegation", count: 38 },
    { label: "Fast delivery", count: 32 },
    { label: "New growth", count: 28 },
    { label: "Great packaging", count: 25 },
  ],
};

export const MOCK_ORDERS = [
  {
    id: "ord-2026-0451",
    orderDate: "2026-05-07T14:30:00Z",
    customerName: "Rahima Begum",
    customerEmail: "rahima@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0448",
    orderDate: "2026-05-06T10:15:00Z",
    customerName: "Karim Ahmed",
    customerEmail: "karim@email.com",
    quantity: 2,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 9000,
    status: "SHIPPED",
    rating: null as number | null,
  },
  {
    id: "ord-2026-0439",
    orderDate: "2026-05-04T16:45:00Z",
    customerName: "Fatima Khan",
    customerEmail: "fatima@email.com",
    quantity: 1,
    variantSku: "ALBO-SML-002",
    variantName: "Juvenile Albo (10cm)",
    unitPrice: 2800,
    totalAmount: 2800,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0432",
    orderDate: "2026-05-02T09:20:00Z",
    customerName: "Sunny Das",
    customerEmail: "sunny@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 3,
  },
  {
    id: "ord-2026-0428",
    orderDate: "2026-05-01T11:00:00Z",
    customerName: "Nusrat Jahan",
    customerEmail: "nusrat@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0415",
    orderDate: "2026-04-28T13:30:00Z",
    customerName: "Tanvir Rahman",
    customerEmail: "tanvir@email.com",
    quantity: 3,
    variantSku: "ALBO-SML-002",
    variantName: "Juvenile Albo (10cm)",
    unitPrice: 2800,
    totalAmount: 8400,
    status: "CANCELLED",
    rating: null as number | null,
  },
  {
    id: "ord-2026-0408",
    orderDate: "2026-04-25T15:10:00Z",
    customerName: "Priya Sharma",
    customerEmail: "priya@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 4,
  },
];

export const MOCK_ACTIVITY = [
  {
    id: "act-001",
    type: "ORDER",
    description: "New order #ord-2026-0451 placed by Rahima Begum",
    timestamp: "2026-05-07T14:30:00Z",
    timeAgo: "Today",
    icon: "shopping-bag",
  },
  {
    id: "act-002",
    type: "REVIEW",
    description: "New 5-star review from Rahima Begum",
    timestamp: "2026-04-28T10:00:00Z",
    timeAgo: "10 days ago",
    icon: "star",
  },
  {
    id: "act-003",
    type: "STOCK",
    description: "Stock updated: 12 units (was 14)",
    timestamp: "2026-04-25T09:00:00Z",
    timeAgo: "13 days ago",
    icon: "cube",
  },
  {
    id: "act-004",
    type: "EDIT",
    description: "Price updated: ৳4,200 → ৳4,500",
    timestamp: "2026-04-20T14:15:00Z",
    timeAgo: "18 days ago",
    icon: "pencil",
  },
  {
    id: "act-005",
    type: "STATUS",
    description: "Status changed from DRAFT to ACTIVE",
    timestamp: "2026-04-15T11:30:00Z",
    timeAgo: "23 days ago",
    icon: "check-circle",
  },
  {
    id: "act-006",
    type: "IMAGE",
    description: "New images added to variant ALBO-MED-001",
    timestamp: "2026-04-12T16:45:00Z",
    timeAgo: "26 days ago",
    icon: "image",
  },
  {
    id: "act-007",
    type: "EDIT",
    description: "Description updated",
    timestamp: "2026-04-10T10:00:00Z",
    timeAgo: "28 days ago",
    icon: "pencil",
  },
  {
    id: "act-008",
    type: "CREATED",
    description: "Plant created",
    timestamp: "2025-12-15T10:30:00Z",
    timeAgo: "4 months ago",
    icon: "plus",
  },
];

export const ACTIVITY_ICON_MAP: Record<string, any> = {
  "shopping-bag": <ShoppingBagIcon class="w-4 h-4 text-cream-600 dark:text-cream-400" />,
  "star": <StarIcon class="w-4 h-4 text-cream-500" />,
  "cube": <CubeIcon class="w-4 h-4 text-gray-500 dark:text-gray-400" />,
  "pencil": <PencilIcon class="w-4 h-4 text-forest-600 dark:text-forest-400" />,
  "check-circle": <CheckCircleIcon class="w-4 h-4 text-forest-600 dark:text-forest-400" />,
  "image": <PackageIcon class="w-4 h-4 text-sage-600 dark:text-sage-400" />,
  "plus": <PlusIcon class="w-4 h-4 text-forest-600 dark:text-forest-400" />,
};
