import type { CartItem, StockStatus } from "~/lib/api/types/cart.types";

export const MOCK_CART_ITEMS: CartItem[] = [
  {
    id: "cart-item-1",
    variantId: "variant-1",
    quantity: 2,
    price: "850",
    lineTotal: "1700",
    productName: "Monstera Deliciosa",
    productSlug: "monstera-deliciosa",
    productType: "plant",
    shopId: "shop-1",
    thumbnail: {
      id: "thumb-1",
      url: "https://images.unsplash.com/photo-1614594975525-e45190c51e8e?w=400&h=400&fit=crop",
    },
    stockStatus: "in_stock" as StockStatus,
    availableQuantity: 15,
    maxQuantity: 10,
    variantAttributes: {
      growthStage: "Mature",
      plantForm: "Standard",
      variegation: "None",
      containerType: "Nursery Pot",
      containerSize: "6 inches",
    },
    variantTitle: "Mature / Standard / 6\"",
    sku: "MON-STD-001",
  },
  {
    id: "cart-item-2",
    variantId: "variant-2",
    quantity: 1,
    price: "1200",
    lineTotal: "1200",
    productName: "Fiddle Leaf Fig",
    productSlug: "fiddle-leaf-fig",
    productType: "plant",
    shopId: "shop-2",
    thumbnail: {
      id: "thumb-2",
      url: "https://images.unsplash.com/photo-1617173944883-66a1941e3f57?w=400&h=400&fit=crop",
    },
    stockStatus: "low_stock" as StockStatus,
    availableQuantity: 3,
    maxQuantity: 3,
    variantAttributes: {
      growthStage: "Young",
      plantForm: "Tree",
      variegation: "None",
      containerType: "Ceramic Pot",
      containerSize: "8 inches",
    },
    variantTitle: "Young / Tree / 8\"",
    sku: "FIG-TRE-002",
  },
  {
    id: "cart-item-3",
    variantId: "variant-3",
    quantity: 3,
    price: "450",
    lineTotal: "1350",
    productName: "Pothos Golden",
    productSlug: "pothos-golden",
    productType: "plant",
    shopId: "shop-1",
    thumbnail: {
      id: "thumb-3",
      url: "https://images.unsplash.com/photo-1596710629128-177937f01e8e?w=400&h=400&fit=crop",
    },
    stockStatus: "in_stock" as StockStatus,
    availableQuantity: 25,
    maxQuantity: 10,
    variantAttributes: {
      growthStage: "Seedling",
      plantForm: "Trailing",
      variegation: "Partial",
      containerType: "Hanging Basket",
      containerSize: "4 inches",
    },
    variantTitle: "Seedling / Trailing / 4\"",
    sku: "POT-TRA-003",
  },
  {
    id: "cart-item-4",
    variantId: "variant-4",
    quantity: 1,
    price: "2500",
    lineTotal: "2500",
    productName: "Pink Princess Philodendron",
    productSlug: "pink-princess-philodendron",
    productType: "plant",
    shopId: "shop-3",
    thumbnail: null,
    stockStatus: "in_stock" as StockStatus,
    availableQuantity: 8,
    maxQuantity: 5,
    variantAttributes: {
      growthStage: "Mature",
      plantForm: "Standard",
      variegation: "Heavy Pink",
      containerType: "Nursery Pot",
      containerSize: "6 inches",
    },
    variantTitle: "Mature / Standard / 6\"",
    sku: "PPR-STD-004",
  },
];
