import { ShoppingBagIcon, StarIcon, CubeIcon, PencilIcon, CheckCircleIcon, PackageIcon, PlusIcon } from "~/components/icons";
import { PRODUCT_STATUS, PRODUCT_TYPE, type ProductStatus, type ProductType, type InventoryDetail } from "~/lib/api/types/seller.types";
import { Component } from "solid-js";

export const MOCK_PRODUCT = {
  id: "prod-001",
  slug: "monstera-deliciosa-albo",
  productType: PRODUCT_TYPE.PLANT as ProductType,
  status: PRODUCT_STATUS.ACTIVE as ProductStatus,
  thumbnail: {
    id: "media-001",
    url: null as string | null,
  },
  name: "Monstera Deliciosa Albo",
  shortDescription: "Stunning variegated Monstera with white-marbled leaves.",
  description: "The Monstera Deliciosa Albo Variegata is one of the most sought-after houseplants in the world. Each leaf features unique white variegation patterns that make every plant truly one-of-a-kind.",
  price: "4500.00",
  inventoryCount: 12,
  totalVariants: 2,
  createdAt: "2025-12-15T10:30:00Z",
  updatedAt: "2026-05-01T14:22:00Z",
};

export const MOCK_PRODUCT_STATS = {
  totalViews: 2847,
  viewsThisMonth: 423,
  viewsChange: "+8%",
  viewsChangeType: "positive" as const,
  totalOrders: 156,
  ordersThisMonth: 23,
  ordersChange: "+15%",
  ordersChangeType: "positive" as const,
  totalRevenue: "702000.00",
  revenueThisMonth: "103500.00",
  revenueChange: "+31%",
  revenueChangeType: "positive" as const,
  avgRating: 4.6,
  totalReviews: 89,
  ratingChange: "+0.2",
  ratingChangeType: "positive" as const,
  conversionRate: 5.5,
  stockTurnover: 3.2,
  revenueThisWeek: "22500.00",
  ordersThisWeek: 5,
  viewsThisWeek: 98,
};

export const MOCK_REVIEWS = [
  {
    id: "rev-001",
    customerName: "Rahima Begum",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Absolutely stunning plant!",
    comment: "The variegation on this Monstera is incredible. Each leaf has unique white patterns. It arrived well-packaged and healthy. Already producing new leaves!",
    date: "2026-04-28T10:00:00Z",
    timeAgo: "10 days ago",
    verifiedPurchase: true,
    images: ["img-review-001", "img-review-002"],
    helpful: 12,
  },
  {
    id: "rev-002",
    customerName: "Karim Ahmed",
    customerAvatar: null as string | null,
    rating: 4,
    title: "Beautiful but needs care",
    comment: "Great plant overall. The variegation is good though not as white as the photos. It's adapting well to my home. Would recommend for experienced plant parents.",
    date: "2026-04-25T14:30:00Z",
    timeAgo: "13 days ago",
    verifiedPurchase: true,
    images: ["img-review-003"],
    helpful: 8,
  },
  {
    id: "rev-003",
    customerName: "Fatima Khan",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Perfect condition, fast delivery",
    comment: "Packaging was excellent. Plant arrived vibrant and healthy. Already has a new leaf unfurling. Very happy with this purchase!",
    date: "2026-04-20T09:15:00Z",
    timeAgo: "18 days ago",
    verifiedPurchase: true,
    images: [] as string[],
    helpful: 15,
  },
  {
    id: "rev-004",
    customerName: "Sunny Das",
    customerAvatar: null as string | null,
    rating: 3,
    title: "Decent plant, some issues",
    comment: "Plant is okay but had some brown edges on arrival. New growth looks healthy though. Variegation is more cream than pure white.",
    date: "2026-04-15T16:45:00Z",
    timeAgo: "23 days ago",
    verifiedPurchase: true,
    images: ["img-review-004"],
    helpful: 5,
  },
  {
    id: "rev-005",
    customerName: "Nusrat Jahan",
    customerAvatar: null as string | null,
    rating: 5,
    title: "Best Albo I've seen locally",
    comment: "I've ordered from multiple sellers and this is by far the best quality Albo Monstera available locally. The variegation is stunning and the plant is very healthy.",
    date: "2026-04-10T11:20:00Z",
    timeAgo: "28 days ago",
    verifiedPurchase: true,
    images: ["img-review-005", "img-review-006", "img-review-007"],
    helpful: 22,
  },
];

export const MOCK_REVIEWS_SUMMARY = {
  average: 4.6,
  total: 89,
  distribution: [
    { stars: 5, count: 62, percentage: 69.7 },
    { stars: 4, count: 18, percentage: 20.2 },
    { stars: 3, count: 6, percentage: 6.7 },
    { stars: 2, count: 2, percentage: 2.2 },
    { stars: 1, count: 1, percentage: 1.1 },
  ],
  highlights: [
    { label: "Healthy arrival", count: 45 },
    { label: "Good variegation", count: 38 },
    { label: "Fast delivery", count: 32 },
    { label: "New growth", count: 28 },
    { label: "Great packaging", count: 25 },
  ],
};

export const MOCK_ORDERS = [
  {
    id: "ord-2026-0451",
    orderDate: "2026-05-07T14:30:00Z",
    customerName: "Rahima Begum",
    customerEmail: "rahima@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0448",
    orderDate: "2026-05-06T10:15:00Z",
    customerName: "Karim Ahmed",
    customerEmail: "karim@email.com",
    quantity: 2,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 9000,
    status: "SHIPPED",
    rating: null as number | null,
  },
  {
    id: "ord-2026-0439",
    orderDate: "2026-05-04T16:45:00Z",
    customerName: "Fatima Khan",
    customerEmail: "fatima@email.com",
    quantity: 1,
    variantSku: "ALBO-SML-002",
    variantName: "Juvenile Albo (10cm)",
    unitPrice: 2800,
    totalAmount: 2800,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0432",
    orderDate: "2026-05-02T09:20:00Z",
    customerName: "Sunny Das",
    customerEmail: "sunny@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 3,
  },
  {
    id: "ord-2026-0428",
    orderDate: "2026-05-01T11:00:00Z",
    customerName: "Nusrat Jahan",
    customerEmail: "nusrat@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 5,
  },
  {
    id: "ord-2026-0415",
    orderDate: "2026-04-28T13:30:00Z",
    customerName: "Tanvir Rahman",
    customerEmail: "tanvir@email.com",
    quantity: 3,
    variantSku: "ALBO-SML-002",
    variantName: "Juvenile Albo (10cm)",
    unitPrice: 2800,
    totalAmount: 8400,
    status: "CANCELLED",
    rating: null as number | null,
  },
  {
    id: "ord-2026-0408",
    orderDate: "2026-04-25T15:10:00Z",
    customerName: "Priya Sharma",
    customerEmail: "priya@email.com",
    quantity: 1,
    variantSku: "ALBO-MED-001",
    variantName: "Mature Albo (15cm)",
    unitPrice: 4500,
    totalAmount: 4500,
    status: "DELIVERED",
    rating: 4,
  },
];

export const MOCK_INVENTORY: InventoryDetail = {
  productId: "prod-001",
  productName: "Monstera Deliciosa Albo",
  productSlug: "monstera-deliciosa-albo",
  totalStock: 12,
  reservedStock: 3,
  availableStock: 9,
  lowStockCount: 1,
  outOfStockCount: 0,
  variants: [
    {
      inventoryId: "inv-001",
      variantId: "var-001",
      sku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      price: "4500.00",
      quantity: 8,
      reservedQuantity: 2,
      availableQuantity: 6,
      lowStockThreshold: 3,
      trackInventory: true,
      allowBackorder: false,
      status: "in_stock" as const,
      lastStockUpdate: "2026-05-01T14:22:00Z",
    },
    {
      inventoryId: "inv-002",
      variantId: "var-002",
      sku: "ALBO-SML-002",
      variantName: "Juvenile Albo (10cm)",
      price: "2800.00",
      quantity: 4,
      reservedQuantity: 1,
      availableQuantity: 3,
      lowStockThreshold: 2,
      trackInventory: true,
      allowBackorder: false,
      status: "low_stock" as const,
      lastStockUpdate: "2026-04-28T09:00:00Z",
    },
    {
      inventoryId: "inv-003",
      variantId: "var-003",
      sku: "ALBO-LRG-003",
      variantName: "Large Albo (20cm)",
      price: "7500.00",
      quantity: 0,
      reservedQuantity: 0,
      availableQuantity: 0,
      lowStockThreshold: 2,
      trackInventory: true,
      allowBackorder: false,
      status: "out_of_stock" as const,
      lastStockUpdate: "2026-04-15T10:00:00Z",
    },
  ],
  stockMovements: [
    {
      id: "mov-001",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "ORDER_RESERVED" as const,
      quantityChange: -1,
      previousQuantity: 9,
      newQuantity: 8,
      previousReserved: 1,
      newReserved: 2,
      referenceType: "order",
      referenceId: "ord-2026-0451",
      reason: "Reserved for order #ord-2026-0451",
      createdBy: "user-001",

      createdAt: "2026-05-07T14:30:00Z",
    },
    {
      id: "mov-002",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "ORDER_RESERVED" as const,
      quantityChange: -2,
      previousQuantity: 10,
      newQuantity: 8,
      previousReserved: 0,
      newReserved: 2,
      referenceType: "order",
      referenceId: "ord-2026-0448",
      reason: "Reserved for order #ord-2026-0448",
      createdBy: "user-001",

      createdAt: "2026-05-06T10:15:00Z",
    },
    {
      id: "mov-003",
      inventoryId: "inv-002",
      variantId: "var-002",
      variantSku: "ALBO-SML-002",
      variantName: "Juvenile Albo (10cm)",
      movementType: "ORDER_RESERVED" as const,
      quantityChange: -1,
      previousQuantity: 5,
      newQuantity: 4,
      previousReserved: 0,
      newReserved: 1,
      referenceType: "order",
      referenceId: "ord-2026-0439",
      reason: "Reserved for order #ord-2026-0439",
      createdBy: "user-001",

      createdAt: "2026-05-04T16:45:00Z",
    },
    {
      id: "mov-004",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "DAMAGED" as const,
      quantityChange: -2,
      previousQuantity: 12,
      newQuantity: 10,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "adjustment",
      referenceId: "adj-001",
      reason: "Damaged stock removed",
      createdBy: "user-001",

      createdAt: "2026-05-01T14:22:00Z",
    },
    {
      id: "mov-005",
      inventoryId: "inv-002",
      variantId: "var-002",
      variantSku: "ALBO-SML-002",
      variantName: "Juvenile Albo (10cm)",
      movementType: "ADJUSTMENT" as const,
      quantityChange: -1,
      previousQuantity: 6,
      newQuantity: 5,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "adjustment",
      referenceId: "adj-002",
      reason: "Quality check failure",
      createdBy: "user-001",

      createdAt: "2026-04-28T09:00:00Z",
    },
    {
      id: "mov-006",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "RESTOCK" as const,
      quantityChange: 5,
      previousQuantity: 7,
      newQuantity: 12,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "purchase_order",
      referenceId: "PO-2026-042",
      reason: "New batch received from nursery",
      createdBy: "user-001",

      createdAt: "2026-04-25T11:00:00Z",
    },
    {
      id: "mov-007",
      inventoryId: "inv-002",
      variantId: "var-002",
      variantSku: "ALBO-SML-002",
      variantName: "Juvenile Albo (10cm)",
      movementType: "RESTOCK" as const,
      quantityChange: 3,
      previousQuantity: 3,
      newQuantity: 6,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "purchase_order",
      referenceId: "PO-2026-042",
      reason: "New batch received from nursery",
      createdBy: "user-001",

      createdAt: "2026-04-20T14:00:00Z",
    },
    {
      id: "mov-008",
      inventoryId: "inv-003",
      variantId: "var-003",
      variantSku: "ALBO-LRG-003",
      variantName: "Large Albo (20cm)",
      movementType: "ORDER_FULFILLED" as const,
      quantityChange: -3,
      previousQuantity: 3,
      newQuantity: 0,
      previousReserved: 3,
      newReserved: 0,
      referenceType: "order",
      referenceId: "ord-2026-0380",
      reason: "Order fulfilled - stock delivered",
      createdBy: null,

      createdAt: "2026-04-15T10:00:00Z",
    },
    {
      id: "mov-009",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "ORDER_FULFILLED" as const,
      quantityChange: -1,
      previousQuantity: 8,
      newQuantity: 7,
      previousReserved: 1,
      newReserved: 0,
      referenceType: "order",
      referenceId: "ord-2026-0410",
      reason: "Order fulfilled - stock delivered",
      createdBy: null,

      createdAt: "2026-04-12T09:30:00Z",
    },
    {
      id: "mov-010",
      inventoryId: "inv-001",
      variantId: "var-001",
      variantSku: "ALBO-MED-001",
      variantName: "Mature Albo (15cm)",
      movementType: "INITIAL_STOCK" as const,
      quantityChange: 8,
      previousQuantity: 0,
      newQuantity: 8,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "initial_setup",
      referenceId: "init-001",
      reason: "Initial stock setup",
      createdBy: "user-001",

      createdAt: "2025-12-15T10:30:00Z",
    },
    {
      id: "mov-011",
      inventoryId: "inv-002",
      variantId: "var-002",
      variantSku: "ALBO-SML-002",
      variantName: "Juvenile Albo (10cm)",
      movementType: "INITIAL_STOCK" as const,
      quantityChange: 3,
      previousQuantity: 0,
      newQuantity: 3,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "initial_setup",
      referenceId: "init-001",
      reason: "Initial stock setup",
      createdBy: "user-001",

      createdAt: "2025-12-15T10:30:00Z",
    },
    {
      id: "mov-012",
      inventoryId: "inv-003",
      variantId: "var-003",
      variantSku: "ALBO-LRG-003",
      variantName: "Large Albo (20cm)",
      movementType: "INITIAL_STOCK" as const,
      quantityChange: 3,
      previousQuantity: 0,
      newQuantity: 3,
      previousReserved: 0,
      newReserved: 0,
      referenceType: "initial_setup",
      referenceId: "init-001",
      reason: "Initial stock setup",
      createdBy: "user-001",

      createdAt: "2025-12-15T10:30:00Z",
    },
  ],
};

export const MOCK_ACTIVITY = [
  {
    id: "act-001",
    type: "ORDER",
    description: "New order #ord-2026-0451 placed by Rahima Begum",
    timestamp: "2026-05-07T14:30:00Z",
    timeAgo: "Today",
    icon: "shopping-bag",
  },
  {
    id: "act-002",
    type: "REVIEW",
    description: "New 5-star review from Rahima Begum",
    timestamp: "2026-04-28T10:00:00Z",
    timeAgo: "10 days ago",
    icon: "star",
  },
  {
    id: "act-003",
    type: "STOCK",
    description: "Stock updated: 12 units (was 14)",
    timestamp: "2026-04-25T09:00:00Z",
    timeAgo: "13 days ago",
    icon: "cube",
  },
  {
    id: "act-004",
    type: "EDIT",
    description: "Price updated: ৳4,200 → ৳4,500",
    timestamp: "2026-04-20T14:15:00Z",
    timeAgo: "18 days ago",
    icon: "pencil",
  },
  {
    id: "act-005",
    type: "STATUS",
    description: "Status changed from DRAFT to ACTIVE",
    timestamp: "2026-04-15T11:30:00Z",
    timeAgo: "23 days ago",
    icon: "check-circle",
  },
  {
    id: "act-006",
    type: "IMAGE",
    description: "New images added to variant ALBO-MED-001",
    timestamp: "2026-04-12T16:45:00Z",
    timeAgo: "26 days ago",
    icon: "image",
  },
  {
    id: "act-007",
    type: "EDIT",
    description: "Description updated",
    timestamp: "2026-04-10T10:00:00Z",
    timeAgo: "28 days ago",
    icon: "pencil",
  },
  {
    id: "act-008",
    type: "CREATED",
    description: "Product created",
    timestamp: "2025-12-15T10:30:00Z",
    timeAgo: "4 months ago",
    icon: "plus",
  },
];

export const ACTIVITY_ICON_MAP: Record<string, Component<{ class?: string }>> = {
  "shopping-bag": ShoppingBagIcon,
  "star": StarIcon,
  "cube": CubeIcon,
  "pencil": PencilIcon,
  "check-circle": CheckCircleIcon,
  "image": PackageIcon,
  "plus": PlusIcon,
};
