import type { PublicPlantListItem } from "~/lib/api/types/public/plants.types";

function createMockPlant(overrides: Partial<PublicPlantListItem> & { id: string; slug: string; name: string; price: string }): PublicPlantListItem {
  const { id, slug, name, price, ...rest } = overrides;
  return {
    id,
    slug,
    name,
    price,
    shortDescription: rest.shortDescription ?? null,
    scientificName: rest.scientificName ?? null,
    commonNames: rest.commonNames ?? null,
    inventoryCount: rest.inventoryCount ?? 0,
    inStock: rest.inStock ?? true,
    thumbnail: rest.thumbnail ?? null,
    category: rest.category ?? null,
    tags: rest.tags ?? [],
    careDifficulty: rest.careDifficulty ?? null,
    lightRequirement: rest.lightRequirement ?? null,
    wateringFrequency: rest.wateringFrequency ?? null,
    humidityLevel: rest.humidityLevel ?? null,
    growthRate: rest.growthRate ?? null,
    shop: rest.shop ?? null,
    createdAt: rest.createdAt ?? "2026-01-01T00:00:00.000Z",
    updatedAt: rest.updatedAt ?? "2026-05-01T00:00:00.000Z",
  };
}

export const MOCK_SIMILAR_PLANTS: PublicPlantListItem[] = [
  createMockPlant({
    id: "mock-1",
    slug: "monstera-albo",
    name: "Monstera Albo Variegata",
    scientificName: "Monstera deliciosa 'Albo'",
    price: "2500",
    inventoryCount: 3,
    inStock: true,
    careDifficulty: "INTERMEDIATE",
    lightRequirement: "BRIGHT_INDIRECT",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t1", slug: "variegated", name: "Variegated" }],
  }),
  createMockPlant({
    id: "mock-2",
    slug: "philodendron-birkin",
    name: "Philodendron Birkin",
    scientificName: "Philodendron birkin",
    price: "800",
    inventoryCount: 12,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "MEDIUM",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t2", slug: "rare", name: "Rare" }],
  }),
  createMockPlant({
    id: "mock-3",
    slug: "syngonium-roseate",
    name: "Syngonium Roseate",
    scientificName: "Syngonium podophyllum",
    price: "350",
    inventoryCount: 8,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "LOW",
    wateringFrequency: "BI_WEEKLY",
    shop: { id: "shop-2", slug: "plant-paradise", name: "Plant Paradise", logo: null },
    tags: [{ id: "t3", slug: "trailing", name: "Trailing" }],
  }),
  createMockPlant({
    id: "mock-4",
    slug: "alocasia-polly",
    name: "Alocasia Polly",
    scientificName: "Alocasia × amazonica",
    price: "650",
    inventoryCount: 0,
    inStock: false,
    careDifficulty: "EXPERT",
    lightRequirement: "BRIGHT_INDIRECT",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-2", slug: "plant-paradise", name: "Plant Paradise", logo: null },
    tags: [{ id: "t4", slug: "tropical", name: "Tropical" }],
  }),
];

export const MOCK_YOU_MIGHT_LIKE: PublicPlantListItem[] = [
  createMockPlant({
    id: "mock-5",
    slug: "fiddle-leaf-fig",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    price: "1800",
    inventoryCount: 5,
    inStock: true,
    careDifficulty: "EXPERT",
    lightRequirement: "DIRECT",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-3", slug: "urban-jungle", name: "Urban Jungle BD", logo: null },
    tags: [{ id: "t5", slug: "statement", name: "Statement" }],
  }),
  createMockPlant({
    id: "mock-6",
    slug: "peperomia-obtusata",
    name: "Peperomia Obtusata",
    scientificName: "Peperomia obtusifolia",
    price: "250",
    inventoryCount: 20,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "MEDIUM",
    wateringFrequency: "BI_WEEKLY",
    shop: { id: "shop-3", slug: "urban-jungle", name: "Urban Jungle BD", logo: null },
    tags: [{ id: "t6", slug: "compact", name: "Compact" }],
  }),
  createMockPlant({
    id: "mock-7",
    slug: "calathea-orbifolia",
    name: "Calathea Orbifolia",
    scientificName: "Goeppertia orbifolia",
    price: "900",
    inventoryCount: 7,
    inStock: true,
    careDifficulty: "INTERMEDIATE",
    lightRequirement: "LOW",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t7", slug: "humidity-lover", name: "Humidity Lover" }],
  }),
  createMockPlant({
    id: "mock-8",
    slug: "string-of-hearts",
    name: "String of Hearts",
    scientificName: "Ceropegia woodii",
    price: "300",
    inventoryCount: 15,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "BRIGHT_INDIRECT",
    wateringFrequency: "BI_WEEKLY",
    shop: { id: "shop-2", slug: "plant-paradise", name: "Plant Paradise", logo: null },
    tags: [{ id: "t8", slug: "trailing", name: "Trailing" }],
  }),
];

export interface MockReview {
  id: string;
  author: string;
  rating: number;
  date: string;
  title: string;
  content: string;
  verified: boolean;
}

export const MOCK_REVIEWS: MockReview[] = [
  {
    id: "r1",
    author: "Fatima Rahman",
    rating: 5,
    date: "2026-05-10",
    title: "Absolutely stunning plant!",
    content: "The Pothos arrived in perfect condition. The leaves are vibrant and healthy. It's been two weeks and it's already producing new growth. Highly recommend this seller!",
    verified: true,
  },
  {
    id: "r2",
    author: "Rafiq Islam",
    rating: 4,
    date: "2026-05-05",
    title: "Great quality, fast delivery",
    content: "Plant was well-packaged and arrived within 2 days. Only giving 4 stars because one leaf had a small tear during shipping. Otherwise, excellent quality for the price.",
    verified: true,
  },
  {
    id: "r3",
    author: "Nusrat Jahan",
    rating: 5,
    date: "2026-04-28",
    title: "Perfect for my apartment",
    content: "This Pothos has completely transformed my living room. It thrives in low light and I forget to water it sometimes but it still looks amazing. The gold variegation is beautiful.",
    verified: true,
  },
  {
    id: "r4",
    author: "Tanvir Ahmed",
    rating: 3,
    date: "2026-04-15",
    title: "Decent but smaller than expected",
    content: "The plant is healthy but smaller than I expected from the photos. It's about 6 inches tall. Will update my review after it grows more. Packaging was good though.",
    verified: true,
  },
];

export const MOCK_MORE_FROM_SHOP: PublicPlantListItem[] = [
  createMockPlant({
    id: "ms1",
    slug: "snake-plant",
    name: "Snake Plant",
    price: "450",
    inventoryCount: 18,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "LOW",
    wateringFrequency: "MONTHLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t9", slug: "air-purifying", name: "Air Purifying" }],
  }),
  createMockPlant({
    id: "ms2",
    slug: "peace-lily",
    name: "Peace Lily",
    price: "550",
    inventoryCount: 10,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "LOW",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t10", slug: "flowering", name: "Flowering" }],
  }),
  createMockPlant({
    id: "ms3",
    slug: "rubber-plant",
    name: "Rubber Plant",
    price: "750",
    inventoryCount: 6,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "MEDIUM",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t11", slug: "large", name: "Large" }],
  }),
  createMockPlant({
    id: "ms4",
    slug: "english-ivy",
    name: "English Ivy",
    price: "300",
    inventoryCount: 14,
    inStock: true,
    careDifficulty: "INTERMEDIATE",
    lightRequirement: "MEDIUM",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t12", slug: "trailing", name: "Trailing" }],
  }),
];

export interface MockBundleItem {
  id: string;
  name: string;
  price: string;
}

export const MOCK_BUNDLE_ITEMS: MockBundleItem[] = [
  { id: "b1", name: "Premium Potting Mix (1kg)", price: "150" },
  { id: "b2", name: "Ceramic Planter (6 inch)", price: "350" },
  { id: "b3", name: "Liquid Fertilizer (250ml)", price: "200" },
];

export const MOCK_RECENTLY_VIEWED: PublicPlantListItem[] = [
  createMockPlant({
    id: "rv1",
    slug: "monstera-deliciosa",
    name: "Monstera Deliciosa",
    price: "1200",
    inventoryCount: 9,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "BRIGHT_INDIRECT",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-2", slug: "plant-paradise", name: "Plant Paradise", logo: null },
    tags: [{ id: "t13", slug: "popular", name: "Popular" }],
  }),
  createMockPlant({
    id: "rv2",
    slug: "bird-nest-fern",
    name: "Bird Nest Fern",
    price: "400",
    inventoryCount: 11,
    inStock: true,
    careDifficulty: "INTERMEDIATE",
    lightRequirement: "LOW",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-3", slug: "urban-jungle", name: "Urban Jungle BD", logo: null },
    tags: [{ id: "t14", slug: "fern", name: "Fern" }],
  }),
  createMockPlant({
    id: "rv3",
    slug: "zz-plant",
    name: "ZZ Plant",
    price: "500",
    inventoryCount: 22,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "LOW",
    wateringFrequency: "BI_WEEKLY",
    shop: { id: "shop-1", slug: "green-haven", name: "Green Haven", logo: null },
    tags: [{ id: "t15", slug: "low-maintenance", name: "Low Maintenance" }],
  }),
  createMockPlant({
    id: "rv4",
    slug: "spider-plant",
    name: "Spider Plant",
    price: "200",
    inventoryCount: 25,
    inStock: true,
    careDifficulty: "BEGINNER",
    lightRequirement: "MEDIUM",
    wateringFrequency: "WEEKLY",
    shop: { id: "shop-2", slug: "plant-paradise", name: "Plant Paradise", logo: null },
    tags: [{ id: "t16", slug: "air-purifying", name: "Air Purifying" }],
  }),
];
